const RequestIDEnum = {
    AUTH_REQUIRED: "AUTH_REQUIRED",
    AUTH_FAILED: "AUTH_FAILED",
    JOIN_STATUS: "JOIN_STATUS",
    PLAY_STATUS: "PLAY_STATUS",
    TOGGLE_PLAY_STATUS: "TOGGLE_PLAY_STATUS",
    JOIN_SPECTATOR_STATUS: "JOIN_SPECTATOR_STATUS",
    DISCONNECT_STATUS: "DISCONNECT_STATUS",
    DISCONNECT_SPECTATOR_STATUS: "DISCONNECT_SPECTATOR_STATUS",
    CREATE_GAME_STATUS: "CREATE_GAME_STATUS",
    MESSAGGE_STATUS: "MESSAGGE_STATUS",
    PLAYED_TURN: "PLAYED_TURN",
    PLAYER_TOGGLED_PLAY: "PLAYER_TOGGLED_PLAY",
    GAME_STARTED: "GAME_STARTED",
    GAME_CONTINUE: "GAME_CONTINUE",
    PLAYER_JOINED: "PLAYER_JOINED",
    GAME_END: "GAME_END",
    SPECTATOR_JOINED: "SPECTATOR_JOINED",
    PLAYER_SENT_MESSAGE: "PLAYER_SENT_MESSAGE",
    PLAYER_DISCONNECTED: "PLAYER_DISCONNECTED",
    SPECTATOR_DISCONNECTED: "SPECTATOR_DISCONNECTED",
    STATS_LOADED: "STATS_LOADED",
    STATS_REQUEST_STATUS: "STATS_REQUEST_STATUS",
    DATABASE_ERROR: "DATABASE_ERROR",
    RECONNECT: "RECONNECT",
    PLAYER_LEFT_ERR: "PLAYER_LEFT_ERR"
}
Object.freeze(RequestIDEnum);
const ResponseIdEnum = {
    JOIN_GAME: "JOIN_GAME",
    PLAY: "PLAY",
    TOGGLE_PLAY: "TOGGLE_PLAY",
    JOIN_SPECTATOR: "JOIN_SPECTATOR",
    DISCONNECT: "DISCONNECT",
    DISCONNECT_SPECTATOR: "DISCONNECT_SPECTATOR",
    CREATE_GAME: "CREATE_GAME",
    SEND_CHAT_MESSAGE: "SEND_CHAT_MESSAGE",
    AUTH: "AUTH"
}
Object.freeze(ResponseIdEnum);

export { RequestIDEnum, ResponseIdEnum }